name: publish to npm
on:
    release:
        types: [created]
jobs:
    build:
        runs-on: ubuntu-latest
        container: node:16-buster

        steps:
            - uses: actions/checkout@v2.4.0
            - run: yarn install
            - run: make clean
            - run: make prepublish -j
            - run: make publish -j
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
